### ISSUE TITLE
(Suggestion:) relation to previous notes

### ISSUE THREAD

**Issue by guillaumew16** [fywalter/CIL-Notes-2020#1]
Hi! First, thanks for making these notes public!

I noticed another repo that seems to do the same thing: https://github.com/dcetin/eth-cs-notes/blob/master/notes/Computational%20Intelligence%20Lab.pdf

Do you think that "ensembling" your notes with that "previous work" (:P) would help to improve them?

**Comment by fywalter** [comment]
Hi! Thanks for the comment. I know this nice repo, and it's very useful during my study of other courses. Still, I have some personal consideration to write a new one for CIL. 

First, the notes in that repo, at least for CIL, seems more like a summary or sketch for review, but I want to write a note that is more like a lecture script (in my own words though hhh), which not only list what is on the slides but also some important supplementary materials and intuition, more importantly it is self-contained for even ones who don't attend the lectures. 

Another reason is that I want to do all thing on my own, which for me is a process towards a deeper understanding.

I will definitely check if we can make things together after I finish the remaining parts:)
